# Target specific macros
TARGET = motor

TARGET_CPP_SOURCES = sample.cpp sample_1.cpp
	
TOPPERS_OSEK_OIL_SOURCE = ./sample.oil

# Don't modify below part
O_PATH ?= build

# makefile for C++(.cpp) build
include ../../../ecrobot/ecrobot++.mak
